development:
  adapter: postgresql
  database: my_database_development
  host: localhost
  pool: 5
  timeout: 5000
  username: toy_app
  password: password1

test:
  adapter: postgresql
  database: my_database_test
  host: localhost
  pool: 5
  timeout: 5000
  username: toy_app
  password: password1

production:
  adapter: postgresql
  database: my_database_production
  host: localhost
  pool: 5
  timeout: 5000
  username: toy_app
  password: password1
